config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :blog_posts

  get "up" => "rails/health#show", as: :rails_health_check

  root "blog_posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :get_blog_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:index, :show]

  def index
    @blog_posts = BlogPost.all
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :body)
  end

  def get_blog_post
    @blog_post = BlogPost.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
  <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <%= form.button %>
<% end %>

app/views/blog_posts/edit.html.erb
<h2>Edit blog post</h2>
<div>
  <%= render partial: 'form', locals: { blog_post: @blog_post } %>
  <%= button_to "Delete", @blog_post, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
</div>

app/views/blog_posts/index.html.erb
<div>
  <% @blog_posts.each do |blog_post| %>
    <div>
      <h3><%= link_to blog_post.title, blog_post %></h3>
      <p><%= blog_post.body %></p>
    </div>
  <% end %>
</div>

app/views/blog_posts/new.html.erb
<h2>Create blog post</h2>
<div>
  <%= render partial: 'form', locals: { blog_post: @blog_post } %>
</div>

app/views/blog_posts/show.html.erb
<div>
  <h2><%= @blog_post.title %></h2>
  <p><%= @blog_post.body %></p>
  <%= link_to "Edit", edit_blog_post_path if admin_signed_in? %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="prose mx-auto my-6">
    <%= render 'partials/navbar' %>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav>
  <%= link_to "Homepage", root_path %>
  <% if admin_signed_in? %>
    <li><%= link_to "New", new_blog_post_path %></li>
    <li><%= link_to "Logout", destroy_admin_session_path, data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?" 
      } %></li>
  <% else %>
    <li><%= link_to "Login", new_admin_session_path %></li>
  <% end %>
</nav>